---
name: "🐛 Bug Report"
description: "Create a report to help us improve"
title: "[BUG]: "
labels: ["bug"]
assignees: ""
body:
  - type: markdown
    attributes:
      value: "<!-- Describe your bugs below ^_^ -->"
  - type: textarea
    id: bug-description
    attributes:
      label: "🐛 Bug description [Please make everyone to understand it]"
      description: "Describe the main elements of the bug"
      placeholder: "Please provide a clear and detailed description of the bug..."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "🧑‍💻 Step to reproduce"
      description: "Describe the steps to reproduce the behavior"
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-result
    attributes:
      label: "👾 Expected result"
      description: "Write down the results you expect"
      placeholder: "I expected that..."
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: "🚑 Any additional information"
      description: "Add any other context, screenshots, or system information here"
      placeholder: "Screenshots, error logs, or other relevant information..."
  - type: input
    id: version
    attributes:
      label: "MineContext Version"
      description: "What version of MineContext are you using?"
      placeholder: "e.g., 0.1.0"
  - type: textarea
    id: platform
    attributes:
        label: "Platform Details"
        description: "Please specify your platform, OS version, and any other relevant system information"
        placeholder: |
            Operating System: 
            Version: 
            Additional Details:
    validations:
        required: true
---