blank_issues_enabled: false
contact_links:
  - name: Get community support
    url: https://bytedance.larkoffice.com/wiki/Hg6VwrxnTiXtWUkgHexcFTqrnpg
    about: Post your question where experienced developers can offer assistance