# Copyright (c) 2025 Beijing Volcano Engine Technology Co., Ltd.
# SPDX-License-Identifier: Apache-2.0
#
# OpenContext Configuration File

# General switch
enabled: true

# Logging configuration
logging:
  level: DEBUG # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_path: "${CONTEXT_PATH:.}/logs/opencontext.log" # Log file path

user_setting_path: "${CONTEXT_PATH:.}/config/user_setting.yaml"

# 文档处理配置
document_processing:
  enabled: true
  batch_size: 3        # Number of images processed by VLM at once (recommended 2-5)
  max_image_size: 1024 # Maximum image size (pixels), larger sizes increase accuracy but also API costs
  dpi: 200             # DPI for converting PDF to images (recommended 150-300)

  # Page-by-page detection configuration (to optimize VLM usage)
  text_threshold_per_page: 50 # Scanned document threshold: pages with fewer characters than this value are considered scanned documents (requires VLM)

vlm_model:
  base_url: "${LLM_BASE_URL}"
  api_key: "${LLM_API_KEY}"
  model: "${LLM_MODEL}"
  provider: ""
  # max_tokens: 4096
  temperature: 0.7

embedding_model:
  base_url: "${EMBEDDING_BASE_URL}"
  api_key: "${EMBEDDING_API_KEY}"
  model: "${EMBEDDING_MODEL}"
  provider: ""
  output_dim: 2048

# Context capture module
capture:
  enabled: true
  # Screenshot capture
  screenshot:
    enabled: false
    capture_interval: 5 # Screenshot interval (seconds)
    storage_path: "${CONTEXT_PATH:.}/screenshots" # Screenshot save directory

  # File monitoring
  file_monitor:
    enabled: false
    recursive: true
    initial_scan: true
    monitor_paths: "./doc"
    capture_interval: 30 # File monitoring interval (seconds)
    # file_patterns:
    #   - "*.txt"
    #   - "*.md"
    #   - "*.py"
    #   - "*.js"
    ignore_patterns:
      - "**/node_modules/**"
      - "**/.git/**"

  # Vaults document monitoring
  vault_document_monitor:
    enabled: false
    monitor_interval: 30 # Monitoring interval (seconds)
    initial_scan: true # Whether to perform an initial scan

# Context processing module
processing:
  enabled: true
  # Document processor configuration
  document_processor:
    enabled: true
    batch_size: 5
    batch_timeout: 30
  screenshot_processor:
    enabled: true
    dedup_cache_size: 30
    similarity_hash_threshold: 5
    batch_size: 20 # Increase batch size to improve throughput
    batch_timeout: 10 # Reduce timeout to improve response speed
    max_image_size: 1920 # Limit image size to reduce memory usage
    resize_quality: 85 # Balance quality and performance
    enabled_delete: true
    max_raw_properties: 5

  # Context merger configuration
  context_merger:
    enabled: false
    # Basic configuration
    similarity_threshold: 0.90
    associative_similarity_threshold: 0.6

    # Intelligent merging configuration
    use_intelligent_merging: true # Enable intelligent strategy merging
    enable_memory_management: true # Enable memory management
    cleanup_interval_hours: 24 # Cleanup check interval

    # Cross-type association configuration
    enable_cross_type_processing: true # Enable cross-type processing
    conversion_confidence_threshold: 0.8 # Conversion confidence threshold
    max_conversions_per_session: 10 # Maximum conversions per session

    # Type-specific configuration
    # Profile type configuration
    ENTITY_CONTEXT_similarity_threshold: 0.85
    ENTITY_CONTEXT_retention_days: 365
    ENTITY_CONTEXT_max_merge_count: 5

    # Activity type configuration
    activity_context_similarity_threshold: 0.80
    activity_context_retention_days: 90
    activity_context_max_merge_count: 3
    activity_context_time_window_hours: 24

    # Intent type configuration
    intent_context_similarity_threshold: 0.75
    intent_context_retention_days: 180
    intent_context_max_merge_count: 4

    # Semantic type configuration
    semantic_context_similarity_threshold: 0.72
    semantic_context_retention_days: 180
    semantic_context_max_merge_count: 6

    # Procedural type configuration
    procedural_context_similarity_threshold: 0.75
    procedural_context_retention_days: 120
    procedural_context_max_merge_count: 4

    # State type configuration
    state_context_similarity_threshold: 0.70
    state_context_retention_days: 7
    state_context_max_merge_count: 10
    state_context_time_window_minutes: 30

# Context storage module
storage:
  enabled: true
  backends:
    - name: "default_vector"
      storage_type: "vector_db"
      backend: "chromadb"
      config:
        mode: "local" # Options: "local", "server"
        path: "${CONTEXT_PATH:.}/persist/chromadb"
        collection_prefix: "opencontext"

    - name: "document_store"
      storage_type: "document_db"
      backend: "sqlite"
      config:
        path: "${CONTEXT_PATH:.}/persist/sqlite/app.db"

# Context consumption module
consumption:
  enabled: true

# web server
web:
  host: "127.0.0.1"
  port: 1733

# API authentication configuration
api_auth:
  enabled: false # Enable authentication in production environment for security
  api_keys:
    - "${CONTEXT_API_KEY:test}"
  excluded_paths:
    - "/health"
    - "/api/health"
    - "/api/auth/status"
    - "/"
    - "/static/*"
    - "/contexts"
    - "/vector_search"
    - "/debug"
    - "/chat"
    - "/advanced_chat"
    - "/monitoring"
    - "/assistant"
    - "/vaults"

# Prompts configuration
prompts:
  language: "zh"

# Content generation service configuration
content_generation:
  # Debug configuration
  debug:
    enabled: false # Enable debug mode to save generation messages and responses
    output_path: "${CONTEXT_PATH:.}/debug/generation" # Debug output directory

  # Task configurations
  activity:
    enabled: true
    interval: 900 # Seconds, minimum 600 (10 minutes), recommended 900-1800 (15-30 minutes)

  tips:
    enabled: true
    interval: 3600 # Seconds, minimum 1800 (30 minutes), recommended 3600-7200 (1-2 hours)

  todos:
    enabled: true
    interval: 1800 # Seconds, minimum 1800 (30 minutes), recommended 1800-3600 (30-60 minutes)

  report:
    enabled: true
    time: "08:00" # Daily report generation time (HH:MM)

tools:
  # Operation tools configuration
  operation_tools:
    web_search_tool:
      enabled: true
      web_search:
        engine: duckduckgo
        max_results: 5
        timeout: 10

# Intelligent completion service configuration
completion:
  enabled: true
